name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f Dockerfile.prod -t webintegral .

      - name: Extract build files
        run: |
          CONTAINER_ID=$(docker create webintegral)
          docker cp $CONTAINER_ID:/usr/share/nginx/html ./build
          docker rm $CONTAINER_ID

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
